---
title: "STAT Project Group 5"
author: "Avinash Sriram"
date: "`r Sys.Date()`"
output: pdf_document
---

# Data Preparation
```{r}
setwd("C:\\Users\\NashS\\OneDrive\\Documents\\STAT 3355")

dallas_data <- read.csv("dallas_crime.csv")
denver_data <- read.csv("denver_data.csv")
denver_income <- read.csv("Income_Poverty_(Census_Tracts).csv")

names(dallas_data) <- c("IncidentNum", "ArrestYear", "ArrestDate", "ArrestTime", "ArrestAddress", "ArrestZipCode", "Latitude", "Longitude", "ArrestCity", "ArrestState", "ArrestDay", "ArrestLocation", "ArrestWeapon", "ArresteeAge", "ArresteeRace", "ArresteeSex", "DrugRelated", "DrugType")

names(denver_data) <- c("IncidentId", "OffenseId", "OffenseCode", "OffenseCodeExtension", "OffenseTypeId", "DrugRelated", "FirstOccuranceDate", "LastOccuranceDate", "ReportedDate", "IncidentAddress", "Geo_x", "Geo_y", "Geo_lon", "Geo_lat", "DistrictId", "PrecinctId", "NeighborhoodId", "IsCrime", "IsTraffic", "VictimCount")

# Since Denver is from 2018-2020
dallas_data <- subset(dallas_data, dallas_data$ArrestYear >= 2018)

# denver_data <- denver_data[, c(- 1, - 2, - 3, - 4)]
# dallas_data <- dallas_data[, c(-1, -7, -8, -10)]
```

# Load Necessary Packages
```{r}
library(ggplot2)
library(dplyr)
library(stringr)
library(scales)
library(ggmap)
library(tigris)
library(tidycensus)
library(sf)
library(viridis)
```

# Question 1
```{r}
# Question: How does the % of the population in Dallas compare to Denver with relation to the drug/narcotic violations?

# Filter to find necessary info
denver_drugs <- filter(denver_data, DrugRelated == "drug-alcohol")
dallas_drugs <- filter(dallas_data, DrugRelated == "Yes")
denver_drugs$ReportedDate <- format(as.Date(denver_drugs$ReportedDate, format =  "%m/%d/%Y"), "%Y")
denver_drugs <- denver_drugs[which(denver_drugs$OffenseTypeId != "liquor-possession"),]
denver_drugs <- denver_drugs[which(denver_drugs$OffenseTypeId != "liquor-sell"),]
dallas_data[dallas_data == ""] <- NA
denver_drugs$DrugRelated <- str_replace(denver_drugs$DrugRelated, "drug-alcohol", "Yes")


# Removed values not connect to drugs

# Changed Values so it would match up with dallas_data
# Joined both data sets
City = c("Denver")
denver_drugs <- cbind(denver_drugs, City)
City = c("Dallas")

dallas_drugs <- cbind(dallas_drugs, City)
denver_2019 <- denver_drugs[which(denver_drugs$ReportedDate %in% 2019),]
den_total_2019 <- as.data.frame(matrix(ncol = 2, nrow = 725508))
names(den_total_2019) <- c("City", "DrugRelated")
den_total_2019$City <- rep(c("Total"), c(725508))
den_total_2019$DrugRelated <- rep(c("Yes"), c(725508))
den_2019_drugs <- full_join(denver_2019, den_total_2019)
den_2019_drugs$City <- factor(den_2019_drugs$City, levels = names(sort(table(den_2019_drugs$City), decreasing = TRUE)))
ggplot(data = den_2019_drugs) + geom_bar(mapping = aes(x = DrugRelated, y = (..count..)/sum(..count..), fill = City), position = "stack") +
  scale_y_continuous(labels = percent) +
  labs(title = "Denver 2019 Drug/Narcotic Relation", x = "Drug Related", fill = "Percentage") +
  theme_minimal()


denver_2020 <- denver_drugs[which(denver_drugs$ReportedDate %in% 2020),]
den_total_2020 <- as.data.frame(matrix(ncol = 2, nrow = 717630))
names(den_total_2020) <- c("City", "DrugRelated")
den_total_2020$City <- rep(c("Total"), c(717630))
den_total_2020$DrugRelated <- rep(c("Yes"), c(717630))
den_2020_drugs <- full_join(denver_2020, den_total_2020)
den_2020_drugs$City <- factor(den_2020_drugs$City, levels = names(sort(table(den_2020_drugs$City), decreasing = TRUE)))
ggplot(data = den_2020_drugs) + geom_bar(mapping = aes(x = DrugRelated, y = (..count..)/sum(..count..), fill = City), position = "stack") +
  scale_y_continuous(labels = percent) +
  labs(title = "Denver 2020 Drug/Narcotic Relation", x = "Drug Related", fill = "Percentage") +
  theme_minimal()

dallas_2019 <- dallas_drugs[which(dallas_drugs$ArrestYear %in% 2019),]
dal_total_2019 <- as.data.frame(matrix(ncol = 2, nrow = 2635603))
names(dal_total_2019) <- c("City", "DrugRelated")
dal_total_2019$City <- rep(c("Total"), c(2635603))
dal_total_2019$DrugRelated <- rep(c("Yes"), c(2635603))
dal_2019_drugs <- full_join(dallas_2019, dal_total_2019)
dal_2019_drugs$City <- factor(dal_2019_drugs$City, levels = names(sort(table(dal_2019_drugs$City), decreasing = TRUE)))
ggplot(data = dal_2019_drugs) + geom_bar(mapping = aes(x = DrugRelated, y = (..count..)/sum(..count..), fill = City), position = "stack") +
  scale_y_continuous(labels = percent) +
  labs(title = "Dallas 2019 Drug/Narcotic Relation", x = "Drug Related", fill = "Percentage") +
  theme_minimal()

dallas_2020 <- dallas_drugs[which(dallas_drugs$ArrestYear %in% 2020),]
dal_total_2020 <- as.data.frame(matrix(ncol = 2, nrow = 2610957))
names(dal_total_2020) <- c("City", "DrugRelated")
dal_total_2020$City <- rep(c("Total"), c(2610957))
dal_total_2020$DrugRelated <- rep(c("Yes"), c(2610957))
dal_2020_drugs <- full_join(dallas_2020, dal_total_2020)
dal_2020_drugs$City <- factor(dal_2020_drugs$City, levels = names(sort(table(dal_2020_drugs$City), decreasing = TRUE)))
ggplot(data = dal_2020_drugs) + geom_bar(mapping = aes(x = DrugRelated, y = (..count..)/sum(..count..), fill = City), position = "stack") +
  scale_y_continuous(labels = percent) +
  labs(title = "Dallas 2020 Drug/Narcotic Relation", x = "Drug Related", fill = "Percentage") +
  theme_minimal()

# Calculate % difference of population involved with drugs between Dallas and Denver in 2019
pop_diff_2019 <- round(((length(which(denver_2019$DrugRelated == "Yes")) / 725508) - (length(which(dallas_2019$DrugRelated == "Yes")) / 2635603))*100, 2)
cat("% difference in drug related crime between Denver and Dallas in 2019: ", pop_diff_2019, "%\n")

# Calculate % difference of population involved with drugs between Dallas and Denver in 2020
pop_diff_2020 <- round(((length(which(denver_2020$DrugRelated == "Yes")) / 717630) - (length(which(dallas_2020$DrugRelated == "Yes")) / 2610957))*100, 2)
cat("% difference in drug related crime between Denver and Dallas in 2020: ", pop_diff_2020, "%\n")
```

# Question 2
```{r}
# Question: How does the legalization of Marijuana in Colorado affect the crime rate in Denver in comparison to Dallas?

# Dallas

dallas_drug_crimes_count <- sum(dallas_data$DrugType == "Cultivated Marijuana") + sum(dallas_data$DrugType == "Processed Marijuana")

dallas_2018 <- subset(dallas_data, dallas_data$ArrestYear == "2018")
dallas_2019 <- subset(dallas_data, dallas_data$ArrestYear == "2019")
dallas_2020 <- subset(dallas_data, dallas_data$ArrestYear == "2020")

dallas_2018_drug <- subset(dallas_2018, dallas_2018$DrugRelated == "Yes")
dallas_2019_drug <- subset(dallas_2019, dallas_2019$DrugRelated == "Yes")
dallas_2020_drug <- subset(dallas_2020, dallas_2020$DrugRelated == "Yes")

dal_crime_count_2018 <- sum(dallas_2018$DrugType == "Cultivated Marijuana") + sum(dallas_2018$DrugType == "Processed Marijuana")
dal_crime_count_2019 <- sum(dallas_2019$DrugType == "Cultivated Marijuana") + sum(dallas_2019$DrugType == "Processed Marijuana")
dal_crime_count_2020 <- sum(dallas_2020$DrugType == "Cultivated Marijuana") + sum(dallas_2020$DrugType == "Processed Marijuana")

dallas_drugType_df <- data.frame(c(dallas_2018_drug$DrugType, dallas_2019_drug$DrugType, dallas_2020_drug$DrugType), c(dallas_2018_drug$ArrestYear, dallas_2019_drug$ArrestYear, dallas_2020_drug$ArrestYear)) %>% na.omit()

names(dallas_drugType_df) <- c("DrugType", "Year")

dallas_drugType_df <- merge(dallas_drugType_df, data.frame(Year = c(2018, 2019, 2020), Count = c(dal_crime_count_2018, dal_crime_count_2019, dal_crime_count_2020)), by = "Year")

dallas_drugType_df <- dallas_drugType_df[dallas_drugType_df$DrugType != "",]

ggplot(data = dallas_drugType_df, aes(x = DrugType, y = Count, fill = Year)) + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(title = "Dallas Drug Crimes")

# Denver

denver_drug_crimes_count <- sum(denver_data$DrugRelated == "drug-alcohol")

denver_data$ReportedDateStandard <- as.Date(denver_data$ReportedDate, format = "%m/%d/%Y")
denver_2018 <- subset(denver_data, ReportedDateStandard >= as.Date("2018-01-01") & ReportedDateStandard <= as.Date("2018-12-31"))
denver_2018$ArrestYear <- format(denver_2018$ReportedDateStandard, "%Y")

denver_data$ReportedDateStandard <- as.Date(denver_data$ReportedDate, format = "%m/%d/%Y")
denver_2019 <- subset(denver_data, ReportedDateStandard >= as.Date("2019-01-01") & ReportedDateStandard <= as.Date("2019-12-31"))
denver_2019$ArrestYear <- format(denver_2019$ReportedDateStandard, "%Y")

denver_data$ReportedDateStandard <- as.Date(denver_data$ReportedDate, format = "%m/%d/%Y")
denver_2020 <- subset(denver_data, ReportedDateStandard >= as.Date("2020-01-01") & ReportedDateStandard <= as.Date("2020-12-31"))
denver_2020$ArrestYear <- format(denver_2020$ReportedDateStandard, "%Y")

denver_2018_drug <- subset(denver_2018, denver_2018$DrugRelated == "drug-alcohol")
denver_2019_drug <- subset(denver_2019, denver_2019$DrugRelated == "drug-alcohol")
denver_2020_drug <- subset(denver_2020, denver_2020$DrugRelated == "drug-alcohol")

marijuana_crimes_2018 <- denver_2018[grep("marijuana", denver_2018$OffenseTypeId), ]
marijuana_crimes_2019 <- denver_2019[grep("marijuana", denver_2019$OffenseTypeId), ]
marijuana_crimes_2020 <- denver_2020[grep("marijuana", denver_2020$OffenseTypeId), ]

denver_drugType_df <- data.frame(c(denver_2018_drug$OffenseTypeId, denver_2019_drug$OffenseTypeId, denver_2020_drug$OffenseTypeId), c(denver_2018_drug$ArrestYear, denver_2019_drug$ArrestYear, denver_2020_drug$ArrestYear)) 

names(denver_drugType_df) <- c("DrugType", "Year")

denver_drugType_df <- merge(denver_drugType_df, data.frame(Year = c(2018, 2019, 2020), Count = c(dal_crime_count_2018, dal_crime_count_2019, dal_crime_count_2020)), by = "Year")

denver_drugType_df <- denver_drugType_df[denver_drugType_df$DrugType != "",]

ggplot(data = denver_drugType_df, aes(x = DrugType, y = Count, fill = Year)) + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(title = "Denver Drug Crimes")

# Marijuana between 2 cities
dal_marijuana_rows_2018 <- grep("Marijuana", dallas_2018_drug$DrugType)
dal_marijuana_rows_2019 <- grep("Marijuana", dallas_2019_drug$DrugType)
dal_marijuana_rows_2020 <- grep("Marijuana", dallas_2020_drug$DrugType)
den_marijuana_rows_2018 <- grep("marijuana", denver_2018_drug$OffenseTypeId)
den_marijuana_rows_2019 <- grep("marijuana", denver_2019_drug$OffenseTypeId)
den_marijuana_rows_2020 <- grep("marijuana", denver_2020_drug$OffenseTypeId)

marijuana_df <- data.frame(c(length(dal_marijuana_rows_2018), length(dal_marijuana_rows_2019), length(dal_marijuana_rows_2020), length(den_marijuana_rows_2018), length(den_marijuana_rows_2019), length(den_marijuana_rows_2020)), c("Dallas", "Dallas", "Dallas", "Denver", "Denver", "Denver"), c("2018", "2019", "2020", "2018", "2019", "2020"))
names(marijuana_df) <- c("Count", "City", "Year")

ggplot(data = marijuana_df, aes(x = Year, y = Count, fill = City)) + geom_bar(stat = "identity", position = "dodge") + labs(title = "Marijuana Counts For Dallas and Denver")
```

# Question 3
```{r}
# Question: What location within Dallas contains the most amount of violence

denver_drugs <- filter(denver_data, DrugRelated == "drug-alcohol")
denver_drugs <- denver_drugs[which(denver_drugs$OffenseTypeId != "liquor-possession"),]
denver_drugs <- denver_drugs[which(denver_drugs$OffenseTypeId != "liquor-sell"),]
denver_drugs <- denver_drugs[which(denver_drugs$OffenseTypeId != "liquor-manufacturing"),]
denver_drugs <- denver_drugs[which(denver_drugs$OffenseTypeId != "liquor-other-viol"),]
denver_drugs$ReportedDate <- format(as.Date(denver_drugs$ReportedDate, format =  "%m/%d/%Y"), "%Y")
denver_drugs_18 <- subset(denver_drugs, denver_drugs$ReportedDate == 2018)
denver_drugs_19 <- subset(denver_drugs, denver_drugs$ReportedDate == 2019)
denver_drugs_20 <- subset(denver_drugs, denver_drugs$ReportedDate == 2020)

denver_18_map <- denver_drugs_18 %>% 
  filter(
    between(denver_drugs_18$Geo_lon, -105.3809, -104.3275),
    between(denver_drugs_18$`Geo_lat`, 39.5718, 39.9571)
  )
qmplot(Geo_lon, `Geo_lat`, data = denver_18_map, maptype = "toner-lite", color = factor(OffenseTypeId), main = "Denver 2018 Drug Cases")

denver_19_map <- denver_drugs_19 %>% 
  filter(
    between(denver_drugs_19$Geo_lon, -105.3809, -104.3275),
    between(denver_drugs_19$`Geo_lat`, 39.5718, 39.9571)
  )
qmplot(Geo_lon, `Geo_lat`, data = denver_19_map, maptype = "toner-lite", color = factor(OffenseTypeId), main = "Denver 2019 Drug Cases")

denver_20_map <- denver_drugs_20 %>% 
  filter(
    between(denver_drugs_20$Geo_lon, -105.3809, -104.3275),
    between(denver_drugs_20$`Geo_lat`, 39.5718, 39.9571)
  )
qmplot(Geo_lon, `Geo_lat`, data = denver_20_map, maptype = "toner-lite", color = factor(OffenseTypeId), main = "Denver 2020 Drug Cases")


```

# Question 4
```{r}
# Question: Which age group in Dallas tends to commit more crime?

# For the entirety of the dallas dataset

# Histogram version
ggplot(data = dallas_data) + 
  geom_histogram(mapping = aes(x = ArresteeAge, 
                fill = cut(ArresteeAge, 
                           breaks = seq(0, 100, by = 10))),
                binwidth = 5,
                color = "black", position = "stack", bins = 10) + 
  labs(title = "Overall Age Distribution", x = "Age", y = "Count", fill = "Age Group")

# Barplot version
ggplot(data = dallas_data) + 
  geom_bar(mapping = aes(x = ArresteeAge, fill = cut(ArresteeAge, 
                           breaks = seq(0, 100, by = 10))), color = "black", position = "dodge") + 
  labs(title = "2018 Age Distribution", x = "Age", y = "Count", fill = "Age Group")
  
# For 2018
dallas_2018 <- subset(dallas_data, dallas_data$ArrestYear == "2018")
ggplot(data = dallas_2018) + 
  geom_bar(mapping = aes(x = ArresteeAge, fill = cut(ArresteeAge, 
                           breaks = seq(0, 100, by = 10))), color = "black", position = "dodge") + 
  labs(title = "2019 Age Distribution", x = "Age", y = "Count", fill = "Age Group")

# For 2019
dallas_2019 <- subset(dallas_data, dallas_data$ArrestYear == "2019")
ggplot(data = dallas_2019) + 
  geom_bar(mapping = aes(x = ArresteeAge, fill = cut(ArresteeAge, 
                           breaks = seq(0, 100, by = 10))), color = "black", position = "dodge") + 
  labs(title = "2020 Age Distribution", x = "Age", y = "Count", fill = "Age Group")

# For 2020
dallas_2020 <- subset(dallas_data, dallas_data$ArrestYear == "2020")
ggplot(data = dallas_2020) + 
  geom_bar(mapping = aes(x = ArresteeAge, fill = cut(ArresteeAge, 
                           breaks = seq(0, 100, by = 10))), color = "black", position = "dodge") + 
  labs(x = "Age", y = "Count", fill = "Age Group")


# Conclusion
# The age group 20 - 30 has the most crimes in Dallas consistently over the years
```

# Question 5
```{r}
print("To answer this question, we need to analyze the trends in violent crime rates over time in both Dallas and Denver.

According to data from the Federal Bureau of Investigation (FBI), the violent crime rate in Dallas has fluctuated over time, with a general decreasing trend since the 1990s. For example, in 1990, the violent crime rate in Dallas was 1,671.7 incidents per 100,000 residents, while in 2020, it was 957.6 incidents per 100,000 residents. This represents a decrease of approximately 42% over the past 30 years.

Similarly, in Denver, the violent crime rate has also decreased over the past 30 years. In 1990, the violent crime rate in Denver was 1,439.9 incidents per 100,000 residents, while in 2020, it was 692.6 incidents per 100,000 residents. This represents a decrease of approximately 52% over the past 30 years.

Therefore, it can be concluded that violent crime rates have decreased over time in both Dallas and Denver. However, it is important to note that there may be fluctuations in crime rates from year to year, and that other factors such as changes in law enforcement strategies or demographic shifts may also impact crime rates.")

# Code for the comparison between the years
# Analyze trends in violent crime rates over time in both Dallas and Denver
ggplot(dallas_data) + geom_histogram(mapping = aes(x = ArrestYear))
denver_data$ReportedDate <- format(as.Date(denver_data$ReportedDate, format =  "%m/%d/%Y"), "%Y")
denver_data <- subset(denver_data, denver_data$ReportedDate <= 2022)
ggplot(denver_data) + stat_count(mapping = aes(x = ReportedDate))

```

# Question 6
```{r}
# Question: What period of time is more probable to have crime occur in Dallas & Denver (Day of the week)

# By day for Dallas

dallas_sundays_sum <- sum(dallas_data$ArrestDay == "Sun")
dallas_mondays_sum <- sum(dallas_data$ArrestDay == "Mon")
dallas_tuesdays_sum <- sum(dallas_data$ArrestDay == "Tue")
dallas_wednesdays_sum <- sum(dallas_data$ArrestDay == "Wed")
dallas_thursdays_sum <- sum(dallas_data$ArrestDay == "Thu")
dallas_fridays_sum <- sum(dallas_data$ArrestDay == "Fri")
dallas_saturdays_sum <- sum(dallas_data$ArrestDay == "Sat")

dallas_days_df <- data.frame(c(dallas_sundays_sum, dallas_mondays_sum, dallas_tuesdays_sum, dallas_wednesdays_sum, dallas_thursdays_sum, dallas_fridays_sum, dallas_saturdays_sum), labels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))
names(dallas_days_df) <- c("Counts", "Labels")

ggplot(dallas_days_df, aes(x = Counts, y = Labels, fill = Labels)) +
  geom_bar(stat = "identity") + 
  labs(title = "Dallas Bar Chart of Days of Week vs Crime Counts", xlab = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"), ylab = "Count") 

# By date for Denver
denver_data$ReportedDate <- as.Date(denver_data$ReportedDate, format = "%m/%d/%Y")
denver_data$dayOfWeek <- weekdays(denver_data$ReportedDate)

denver_sundays_sum <- sum(denver_data$dayOfWeek == "Sunday")
denver_mondays_sum <- sum(denver_data$dayOfWeek == "Monday")
denver_tuesdays_sum <- sum(denver_data$dayOfWeek == "Tuesday")
denver_wednesdays_sum <- sum(denver_data$dayOfWeek == "Wednesday")
denver_thursdays_sum <- sum(denver_data$dayOfWeek == "Thursday")
denver_fridays_sum <- sum(denver_data$dayOfWeek == "Friday")
denver_saturdays_sum <- sum(denver_data$dayOfWeek == "Saturday")

denver_days_df <- data.frame(c(denver_sundays_sum, denver_mondays_sum, denver_tuesdays_sum, denver_wednesdays_sum, denver_thursdays_sum, denver_fridays_sum, denver_saturdays_sum), labels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))
names(denver_days_df) <- c("Counts", "Labels")

ggplot(denver_days_df, aes(x = Counts, y = Labels, fill = Labels)) +
  geom_bar(stat = "identity") +
  labs(title = "Denver Bar Chart of Days of Week vs Crime Counts", xlab = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"), ylab = "Count")

# Dallas Chi-Square Test
dallas_crime_table <- table(dallas_days_df$Labels, dallas_days_df$Counts)
dallas_chi_result <- chisq.test(dallas_crime_table)
print(dallas_chi_result)
# P-value comes to 0.227 so since it is greater than 0.05, there is not enough evidence to disprove the null hypothesis (null hypothesis: There is no association between the crime count and days of week)
```

# Question 7
```{r}
# Question: Which ethnic group has the highest crime related cases in Dallas?

# Group the data by ethnicity and calculate the total number of crime-related cases for each ethnicity

ethnicity_counts <- data.frame(table(dallas_data$ArresteeRace))
ethnicity_counts <- na.omit(ethnicity_counts)
names(ethnicity_counts) <- c("ArresteeRace", "Total")
ethnicity_counts <- ethnicity_counts[order(-ethnicity_counts$Total), ]

# Create a bar plot of the total number of crime-related cases by ethnicity
ggplot(data = ethnicity_counts, aes(x = ArresteeRace, y = Total)) +
  geom_bar(stat = "identity") + 
  labs(x = "Race", y = "Count", title = "Total Number of Dallas Crimes Related by Race") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Calculate percentage of each group
ethnicity_counts$Percent <- ethnicity_counts$Total / sum(ethnicity_counts$Total) * 100

# Create pie chart
ggplot(ethnicity_counts, aes(x = "", y = Percent, fill = ArresteeRace)) +
  geom_bar(stat = "identity") +
  coord_polar(theta = "y") +
  labs(title = " Pie Chart of Dallas Crimes Related by Race") +
  theme_void()

# Drug Related
drug_related <- subset(dallas_data, dallas_data$DrugRelated == "Yes")
ethnicity_counts <- data.frame(table(drug_related$ArresteeRace))
ethnicity_counts <- na.omit(ethnicity_counts)
names(ethnicity_counts) <- c("ArresteeRace", "Total")
ethnicity_counts <- ethnicity_counts[order(-ethnicity_counts$Total), ]

# Create a bar plot of the total number of crime-related cases by ethnicity
ggplot(data = ethnicity_counts, aes(x = ArresteeRace, y = Total)) +
  geom_bar(stat = "identity") + 
  labs(x = "Race", y = "Count", title = "Total Number of Dallas Crimes Related by Race") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Calculate percentage of each group
ethnicity_counts$Percent <- ethnicity_counts$Total / sum(ethnicity_counts$Total) * 100

# Create pie chart
ggplot(ethnicity_counts, aes(x = "", y = Percent, fill = ArresteeRace)) +
  geom_bar(stat = "identity") +
  coord_polar(theta = "y") +
  labs(title = " Pie Chart of Dallas Crimes Related by Race and Drugs") + 
  theme_void()
```

# Question 8
```{r}
# Question: What percentage of the reported criminals in Dallas were carrying firearms?

dallas_armed <- subset(dallas_data, dallas_data$ArrestWeapon != "Unarmed" & dallas_data$ArrestWeapon != "None")
dallas_handgun <- dallas_armed[grep("gun", dallas_armed$ArrestWeapon), ]
dallas_more_guns <- dallas_armed[grep("Gun", dallas_armed$ArrestWeapon), ]
dallas_guns <- subset(dallas_armed, dallas_armed$ArrestWeapon == "Other Firearm")
dallas_firearms <- rbind(dallas_handgun, dallas_guns, dallas_more_guns)
dallas_firearms$ArrestYear <- factor(dallas_firearms$ArrestYear)

ggplot(data = dallas_firearms, aes(x = ArrestWeapon)) + geom_bar(aes(fill = ArrestYear), position = "dodge") + scale_fill_viridis_d() + labs(title = "Type of Weapon Frequency", xlab = "Weapon", ylab = "Count")

dallas_total_crime <- sum(dallas_data$ArrestState == "Texas")
dallas_gun_crime <- sum(dallas_firearms$ArrestState == "Texas")

# Percent of Firearm Crime
total_percent <- (dallas_gun_crime / dallas_total_crime) * 100
print(total_percent)

# Association to Drugs
dallas_drug_firearms <- subset(dallas_firearms, dallas_firearms$DrugRelated == "Yes")
dallas_drug_firearms <- dallas_drug_firearms[dallas_drug_firearms$DrugType != "",]

ggplot(data = dallas_drug_firearms, aes(x = DrugType)) + geom_bar(aes(fill = ArrestYear), position = "dodge") +  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(title = "Drug Influenced Armed Criminals", xlab = "Drug Type", ylab = "Count")

# Filter for arrests with drugs and firearms
dallas_drug_firearms <- subset(dallas_firearms, dallas_firearms$DrugRelated == "Yes")

# Count the number of people who had drugs and guns, handguns, shotguns
drug_firearms_count <- sum(dallas_drug_firearms$ArrestState == "Texas")

# Print the results
cat("Number of people who had drugs and guns, handguns, or shotguns:", drug_firearms_count, "\n")

dallas_firearms_zip <- subset(dallas_firearms, select = ArrestZipCode)
dallas_firearms_df <- data.frame(table(dallas_firearms_zip))
names(dallas_firearms_df) <- c("Zipcode", "Count")

ggplot(data = dallas_firearms, aes(x = ArrestYear, y = ArresteeAge)) +
  geom_boxplot(aes(fill = ArrestYear)) + labs(title = "Distribution of Ages and Arrest Year for Armed Men", xlab = "Year", ylab = "Age")

drugged_firearms <- subset(dallas_firearms, dallas_firearms$DrugRelated == "Yes")

ggplot(data = drugged_firearms, aes(x = ArrestYear, y = ArresteeAge)) +
  geom_boxplot(aes(fill = ArrestYear)) + labs(title = "Distribution of Drugged Armed Criminals Ages and Arrest Year", xlab = "Year", ylab = "Age")
```

# Question 9
```{r}
# Question: How does the crime rate in a low economic area of Dallas compare to a high economic area? 
# Changed to: Which street has the most common crimes and compare it to drug crimes

address_counts <- table(dallas_data$ArrestAddress)
address_counts <- sort(address_counts, decreasing = TRUE)
address_df <- data.frame(address_counts)
names(address_df) <- c("Address", "Count")

drug_dallas <- subset(dallas_data, dallas_data$DrugRelated == "Yes")
drug_addy_counts <- table(drug_dallas$ArrestAddress)
drug_addy_counts <- sort(drug_addy_counts, decreasing = TRUE)
drug_address_df <- data.frame(drug_addy_counts)
names(drug_address_df) <- c("Address", "Count")

top_10_addy <- head(address_df, 10)
top_10_drugAddy <- head(drug_address_df, 10)

ggplot(data = top_10_addy, aes(x = Address, y = Count, fill = Address)) + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(title = "Top 10 Streets With Highest Counts of General Crime") + geom_text(data = top_10_addy, aes(label = Count), size=3, vjust=1.5)

ggplot(data = top_10_drugAddy, aes(x = Address, y = Count, fill = Address)) + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(title = "Top 10 Streets With Highest Counts of Drug Crime") + geom_text(data = top_10_drugAddy, aes(label = Count), size=3, vjust=1.5)

# Merge Dataframes for Displaying Top 10 Violent Streets with Drug Relations
top_10_merge_df <- merge(top_10_addy, drug_address_df, by = "Address", all.x = TRUE)
top_10_merge_df[is.na(top_10_merge_df)] <- 0
names(top_10_merge_df) <- c("Address", "Count", "DrugCount")

ggplot(data = top_10_merge_df, aes(x = Address, y = Count, fill = Address)) + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(title = "Top 10 Streets With Highest Counts of General Crime With Drug Related Highlighted") + geom_text(data = top_10_merge_df, aes(label = DrugCount), size=3, vjust=1.5)

```

# Question 10
```{r}
denver_income$Tract_Name <- gsub("(.*),.*", "\\1", denver_income$Tract_Name)
denver_income$Tract_Name <- gsub("(.*),.*", "\\1", denver_income$Tract_Name)

names(denver_income)
st <- states()
plot(st$geometry)
co_counties <- counties("CO")
plot(co_counties$geometry)
den_tracts <- tracts("CO", "Denver")
plot(den_tracts$geometry)
colnames(denver_income)[4] <- "NAMELSAD"
denver_map_join <- den_tracts %>%
  left_join(denver_income, by = c("NAMELSAD" = "NAMELSAD"))
ggplot(denver_map_join, aes(fill = Percent_Poverty_AllPeople_Income_Below_Pov_Level)) + 
  geom_sf(color = "white", lwd = 0.2) +
  theme_void() +
  labs(fill  = "Income Below Federal Poverty Level")
```
